<a href="https://colab.research.google.com/github/soodeh-nilforoushan/Recurrent-Neural-Network/blob/main/7_TF_RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
from tensorflow.keras.layers import Input, Dense, Flatten, SimpleRNN
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# N=number of samples
# T=sequence length
# D=number of input features
# M=number of hidden unites
# K=number of output units

In [6]:
#Make some data
N=1
T=10
D=3
K=2
X=np.random.randn(N,T,D)
print(X)

[[[ 0.96415351 -0.32766151 -0.83264496]
  [ 1.18821148 -0.95587978 -0.63281209]
  [ 0.49629085 -1.32032286  0.1856647 ]
  [ 0.94511146  0.21273143  1.43388822]
  [ 0.56099855  0.02041168  0.66904066]
  [-0.98858077 -1.74809208  0.04803899]
  [ 0.71418951  0.43606031  1.16335782]
  [-0.07931035 -0.36437869 -2.43256712]
  [-0.7075999   0.83161351 -0.16246651]
  [ 1.60094987  1.93938013 -1.66356615]]]


In [11]:
#make a RNN
M=5 #number of hidden units
i=Input(shape=(T,D))
#simple RNN layer which has the number of hidden units m. Let's assume the default activation, which is a  Thanh.
x=SimpleRNN(M)(i)
x=Dense(K)(x)
model=Model(i,x)


In [14]:
#get the output
Yhat=model.predict(X)
print(Yhat)
#both our data and weights are random, so this prediction is not meaningful.
#These numbers are really just for sanity checking.

1/1 [==============================] - 0s 16ms/step
[[-1.8315885  1.0609448]]


In [15]:
#Next we can do a model summary so that we can see all the layers of our RNN.
model.summary()


Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense_3 (Dense)             (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [16]:
#see what is returend
model.layers[1].get_weights()

[array([[ 0.5466134 , -0.6805535 , -0.6224454 ,  0.8011251 , -0.20999926],
        [ 0.6383043 ,  0.630971  , -0.35103387,  0.8517476 ,  0.54200464],
        [-0.03232884, -0.44037172, -0.36466402,  0.3240375 ,  0.5365495 ]],
       dtype=float32),
 array([[-0.22596276,  0.20312642,  0.560819  ,  0.7539082 , -0.15743303],
        [ 0.14271495,  0.62257   , -0.67403036,  0.36970937, -0.03220384],
        [-0.09012795,  0.55602187,  0.31629795, -0.26242718,  0.71680135],
        [ 0.69811887,  0.3564884 ,  0.36210012, -0.24790093, -0.43928882],
        [-0.6580884 ,  0.36728996,  0.00207159, -0.40572724, -0.5171063 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [17]:

#check the shapes
# we can deduce which array corresponds to which weight in the simple rnn.
# The first weight is D by M, which means it's the input to hidden weight.
# The second weight is M by M, which means it's the hidden to hidden weight.
#third weight is a vector of length M, which means it's the bias term.
a,b,c=model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [19]:
Wx,Wh,bh=model.layers[1].get_weights()
Wo, bo=model.layers[2].get_weights()

In [22]:
h_last=np.zeros(M)
x=X[0]
Yhats=[]

for t in range(T):
  h=np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
  y=h.dot(Wo)+bo #we only care about this value on the last iteration
  Yhats.append(y)

  #assign h to h_last
  h_last=h

#print the final output
print(Yhats[-1])

[-1.8315885   1.06094479]


We've confirmed that these are indeed the calculations that are done in the simple RNN in box 14