<a href="https://colab.research.google.com/github/soodeh-nilforoushan/Recurrent-Neural-Network/blob/main/TF_Text_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install -q tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [4]:
#just a simple test
sentences=[
    "I like eggs and ham.",
    "I love chocolote an bunnies.",
    "I hate onions."
]

In [10]:
from typing import Sequence
MAX_VOCAB_SIZE=20000 #The Oxford Dictionary has almost 200,000 words, but the most common words in the English language number only about 3000.
tokenizer=Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences=tokenizer.texts_to_sequences(sentences)

In [11]:
print(sequences)
#note that the integers start counting from one and not zero, as you might have expected.
# this is because TensorFlow uses zero for padding.

[[1, 2, 3, 4, 5], [1, 6, 7, 8, 9], [1, 10, 11]]


In [8]:
#how to get the word to index mapping?
tokenizer.word_index

{'i': 1,
 'like': 2,
 'eggs': 3,
 'and': 4,
 'ham': 5,
 'love': 6,
 'chocolote': 7,
 'an': 8,
 'bunnies': 9,
 'hate': 10,
 'onions': 11}

In [14]:
#use the defaults
data=pad_sequences(sequences)
print(data)
# there is padding for the third sentence at the beggining

[[ 1  2  3  4  5]
 [ 1  6  7  8  9]
 [ 0  0  1 10 11]]


In [15]:
MAX_SEQUENCE_LENGTH=5
data=pad_sequences(sequences,maxlen=MAX_SEQUENCE_LENGTH,padding="post")
print(data)
#we can see that if we explicitly pass in maxlen equals five, we get the same answer.

[[ 1  2  3  4  5]
 [ 1  6  7  8  9]
 [ 1 10 11  0  0]]


In [17]:
#too much padding
data=pad_sequences(sequences,maxlen=6)
print(data)

[[ 0  1  2  3  4  5]
 [ 0  1  6  7  8  9]
 [ 0  0  0  1 10 11]]


In [18]:
#truncation
data=pad_sequences(sequences,maxlen=4)
print(data)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [ 0  1 10 11]]


In [19]:
#truncation
data=pad_sequences(sequences,maxlen=4,truncating="post")
print(data)

[[ 1  2  3  4]
 [ 1  6  7  8]
 [ 0  1 10 11]]
